### ISSUE TITLE
superagent.get(...).buffer is not a function

### ISSUE THREAD

**Issue by iaq3** [visionmedia/superagent#1517]
installed through npm

Having trouble using simple buffer function.
```
const superagent = require('superagent');

superagent.get(url).buffer(true).parse(superagent.parse.image)
      .then((res) => res) 
```

results in 
```superagent.get(...).buffer is not a function```

Any help would be greatly appreciated, from all the guides and sample code I've read through, this should work fine.

**Comment by Levino** [comment]
For me it works in node but I get the same error in the browser

**Comment by k-funk** [comment]
Getting the same error When upgrading from 4.1.0 -> 5.x:
```
request.get('/file.json').buffer(true).parse(r => r);
```

**Comment by niftylettuce** [comment]
PR welcome if you can find the fix!

**Comment by Levino** [comment]
I wrote a try catch statement:
Try to use the node syntax, if that fails, try to use the browser syntax. Worked even though it is a bit ugly. I think the api of the library should not change between node and browser...

**Comment by niftylettuce** [comment]
OK I see the issue.

In the older version, client version had this:

https://github.com/visionmedia/superagent/blob/v4.1.0/lib/client.js#L631-L635

In newer version, we have this:

```js
Request.prototype.buffer = Request.prototype.ca;
Request.prototype.ca = Request.prototype.agent;
```

The order in the newer version when I did the rewrite got reversed.  I'm fixing it now and publishing a new version.

**Comment by niftylettuce** [comment]
@iaq3 @Levino @k-funk @dews please try the latest version of superagent I just published to npm, v5.2.1

```sh
npm install superagent@latest`
```

or with yarn:

```sh
yarn add superagent@latest
```

**Comment by Levino** [comment]
Very good. Unfortunately I meanwhile have a different code that is only run on the server so we do not need the fix any more...

**Comment by k-funk** [comment]
@niftylettuce 5.2.1 fixed the bug for me. Thank you!
